# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: During a journey
email: milena.lavanchy@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
# among a wide number of life sciences organizations and communities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://milenalavanchy.github.io" # the base hostname & protocol for your site
github_username:  MilenaLavanchy

# Build settings
markdown: kramdown

# Gems
plugins:
 - jekyll-redirect-from
 - jekyll-sitemap


collections:
  cats:
    output: true
